# Correr experimentos
En este archivo está el código para correr los experimentos y escribir los resultados en archivos CSV.
> Los archivos se guardan en la carpeta _resultados_.

In [1]:
import math, subprocess
import pandas as pd
import numpy as np
from IPython.display import display, clear_output

A continuación leemos los datasets en dataframes de Pandas.

In [2]:
def leer_instancia(path_instancia):
    with open(path_instancia, "r") as f:
        return f.read();

La siguiente función sirve para correr el código sobre una instancia ejecutando un método en particular.

- **VMC** : vecino mas cercano
- **AGM** : arbol generador minimo
- **I** : incersion
- **tabu falta** : tabu

In [57]:
def correr_experimento(metodo, archivo_instancia,parametros_tabu):
    # Leer archivo de la instancia.
    instancia = leer_instancia(archivo_instancia)
    
    cmds = ["../tp2", metodo] + parametros_tabu
    # Crear proceso para ejecutar el codigo.
    process = subprocess.Popen(cmds , stderr=subprocess.PIPE, stdout=subprocess.PIPE, stdin=subprocess.PIPE, universal_newlines = True)

    # Poner la instancia en la entrada estandar.
    process.stdin.write(instancia)
    process.stdin.flush()

    # Correr experimento.
    exit_code = process.wait()

    # Verificar que el proceso no fallo.
    if exit_code != 0: raise(f"Hubo un error en la experimentacion para el algoritmo: {metodo} con la instancia {archivo_instancia}.")
    # Leer salida de STDERR con los tiempos de ejecucion de cada metodo.
    tiempo_de_ejecucion = float(process.stderr.read());
    costo = process.stdout.read() 
    #print(process.stdout.read()) # resultado del metodo
    process.stdin.close();
    process.stdout.close();
    process.stderr.close();
    costo = costo.split(" ")[1]
    costo = costo.split("\n")[0]
    res = (tiempo_de_ejecucion,float(costo))
    
    return res;

## Corremos los experimentos
Vamos a guardar una tabla con las ejecuciones y sus respectivos tiempos.

In [49]:
experimentos = [];
experimentos

[]

In [32]:
# n : cantidad de vertices del grafo
#Inicios: todos los v de cada arista v->w
#Destinos: todos los w de cada arista v->w
#Pesos: todos los pesos de cada arista v->w

def save_instance(dataset, instance_name,n, Inicios,Destinos, Pesos):
    with open(F"{dataset}/{instance_name}.txt", "w") as f:
        
        print(n, len(Inicios), file=f)

        for i in range(len(Pesos)): 
            print(Inicios[i], file=f, end=" ")
            print(Destinos[i], file=f, end=" ")
            print(Pesos[i], file=f)
            

def save_index(dataset, instances):
    with open(F"instancias/{dataset}/instances.txt", "w") as f:
        for instance in instances: 
            print(instance, file=f)

In [37]:
def gen_vmc(n):
    Inicios = []
    Destinos = []
    Pesos= []
    pesocierre = 100
    #CHEQUEAR INDICES i J
    for i in range(1,n+1):
        for j in range(i+1,n+1):
            Inicios.append(i)
            Destinos.append(j)
            if(i == 0 and j==n-1):
                Pesos.append(pesocierre)
            else:
                Pesos.append(1)

    return Inicios,Destinos,Pesos

In [47]:
archivos_instancia= []
for n in range(5,55,5):
    
    Inicios,Destinos,Pesos = gen_vmc(n)
    dataset = "instancias_exp_vmc"
    instance_name = f"vmc_{n}"    
    save_instance(dataset, instance_name,n, Inicios,Destinos, Pesos)
    archivos_instancia.append(F"{dataset}/{instance_name}.txt")

In [48]:
archivos_instancia

['instancias_exp_vmc/vmc_5.txt',
 'instancias_exp_vmc/vmc_10.txt',
 'instancias_exp_vmc/vmc_15.txt',
 'instancias_exp_vmc/vmc_20.txt',
 'instancias_exp_vmc/vmc_25.txt',
 'instancias_exp_vmc/vmc_30.txt',
 'instancias_exp_vmc/vmc_35.txt',
 'instancias_exp_vmc/vmc_40.txt',
 'instancias_exp_vmc/vmc_45.txt',
 'instancias_exp_vmc/vmc_50.txt']

In [52]:
experimentos = []
i = 0
for n in range(5,55,5):
    experimentos.append(["vmc_exp", n ,"VMC", archivos_instancia[i] ,[0,0,0,0]]);
    i+=1

In [56]:
correr_experimento(metodo, archivo_instancia,parametros_tabu):

SyntaxError: invalid syntax (<ipython-input-56-26b8a53e2fd5>, line 1)

In [55]:

exp = correr_experimento("VMC", 'instancias_salida/burma14.txt',[0,0,0,0])

TypeError: expected str, bytes or os.PathLike object, not int

## CORRER EXPERIMENTOS

In [53]:
columnas = ["dataset", "n", "metodo", "tiempo","costo","largolista","max_iter","rang_iter","percentage",];

filas = [];
numero = 1
T = 5 # Numero de veces que se ejecuta cada experimento (para mayor fidelidad del tiempo).
for experimento in experimentos:
    # Voy mostrando que experimento se esta ejecutando.
    clear_output(wait=True)
    display('Experimento: ' + str(numero) + "/" + str(len(experimentos)))
    numero += 1
    
    # Ejecutamos el experimento T veces y obtenemos la mediana.
    tiempos = []
    costos = []
    resultados = []
    for i in range(0, T):
        exp = correr_experimento(experimento[2], experimento[3],experimento[4])
        t = exp[0]
        c = exp[1]
        costos.append(c)
        tiempos.append(t);
    costo = np.median(costos)
    tiempo = np.median(tiempos);
    filas.append([experimento[0], experimento[1], experimento[2], tiempo,costo,
                  experimento[4][0],experimento[4][1],experimento[4][2],experimento[4][3]]);
print('fin :)')

'Experimento: 1/10'

TypeError: expected str, bytes or os.PathLike object, not int

In [31]:
df_resultados = pd.DataFrame(filas, columns=columnas);

#df_resultados.to_csv("resultados/resultado.csv", index=False, header=True);

In [33]:
print("AGM-TS1 con 100% vecinos")
df_resultados

AGM-TS1 con 100% vecinos

,dataset,n,metodo,tiempo,costo,largolista,max_iter,rang_iter,percentage
0,ch150,150,AGM-TS1,9138.49,7546.0,200,500,50,100

In [ ]:
df_resultados.to_csv("expComparacion.csv", index=False, header=True);

In [ ]:
811965

In [91]:
df_resultados

,dataset,n,metodo,tiempo,costo,largolista,max_iter,rang_iter,percentage
0,berlin52,52,AGM-TS1,110.460,10402.0,50,1000,50,5
1,berlin52,52,AGM-TS1,112.365,10402.0,100,1000,50,5
2,berlin52,52,AGM-TS1,123.477,10402.0,200,1000,50,5
3,berlin52,52,AGM-TS1,356.553,9468.0,50,1000,50,30
4,berlin52,52,AGM-TS1,345.430,9493.0,100,1000,50,30
...,...,...,...,...,...,...,...,...,...
211,berlin52,52,I-TS2,567.208,8370.0,100,1000,300,50
212,berlin52,52,I-TS2,572.984,8497.0,200,1000,300,50
213,berlin52,52,I-TS2,1016.900,7866.0,50,1000,300,100
214,berlin52,52,I-TS2,1023.090,7887.0,100,1000,300,100
215,berlin52,52,I-TS2,1022.080,7811.0,200,1000,300,100

In [92]:
df_viejo = pd.read_csv("resultados/resultado.csv")

In [93]:
df_viejo

,dataset,n,metodo,tiempo,costo,largolista,max_iter,rang_iter,percentage
0,berlin52,52,AGM-TS1,5.750460,10402.0,50,50,50,5
1,berlin52,52,AGM-TS1,5.450580,10402.0,100,50,50,5
2,berlin52,52,AGM-TS1,5.540750,10402.0,200,50,50,5
3,berlin52,52,AGM-TS1,15.778300,9896.0,50,50,50,30
4,berlin52,52,AGM-TS1,15.721000,9896.0,100,50,50,30
...,...,...,...,...,...,...,...,...,...
646,berlin52,52,I-TS2,498.997000,8052.0,100,500,300,100
647,berlin52,52,I-TS2,493.535000,8067.0,200,500,300,100
648,berlin52,52,AGM,0.122992,10402.0,0,0,0,0
649,berlin52,52,VMC,0.077672,8980.0,0,0,0,0
650,berlin52,52,I,32.040800,15771.0,0,0,0,0

In [94]:
df_nuevo = df_viejo.append(df_resultados, ignore_index = True)
df_nuevo

,dataset,n,metodo,tiempo,costo,largolista,max_iter,rang_iter,percentage
0,berlin52,52,AGM-TS1,5.75046,10402.0,50,50,50,5
1,berlin52,52,AGM-TS1,5.45058,10402.0,100,50,50,5
2,berlin52,52,AGM-TS1,5.54075,10402.0,200,50,50,5
3,berlin52,52,AGM-TS1,15.77830,9896.0,50,50,50,30
4,berlin52,52,AGM-TS1,15.72100,9896.0,100,50,50,30
...,...,...,...,...,...,...,...,...,...
862,berlin52,52,I-TS2,567.20800,8370.0,100,1000,300,50
863,berlin52,52,I-TS2,572.98400,8497.0,200,1000,300,50
864,berlin52,52,I-TS2,1016.90000,7866.0,50,1000,300,100
865,berlin52,52,I-TS2,1023.09000,7887.0,100,1000,300,100
866,berlin52,52,I-TS2,1022.08000,7811.0,200,1000,300,100

In [95]:
df_nuevo.to_csv("resultados/resultado.csv", index=False, header=True);